In [1]:
import numpy as np 

arr = np.array([101,201,301,401,501]) 

print(arr) 

print(type(arr))

[101 201 301 401 501]
<class 'numpy.ndarray'>


In [3]:
import numpy as np 

nameList = ['Angel',"Shemi","Marvel","Linda"] 
ageTuple = (41,32,21,19)
gradeDict = {"CSC102": 89,"MTH 102": 77,"CHM 102":69, "GST 102":99 } 

arr_nameList = np.array(nameList) 
arr_ageTuple = np.array(ageTuple) 
arr_gradeDict = np.array(gradeDict) 

print(arr_nameList) 
print(arr_ageTuple) 
print(arr_gradeDict) 

['Angel' 'Shemi' 'Marvel' 'Linda']
[41 32 21 19]
{'CSC102': 89, 'MTH 102': 77, 'CHM 102': 69, 'GST 102': 99}


In [8]:
import numpy as np 

classNum = int(input("How many students are in the CSC 102 class? ")) 
class_arr = np.array(classNum)

if class_arr ==1: 
    print("There is only ", class_arr , "student in CSC 102 class ")
    
else: 
    print("There are", class_arr,"students in CSC 102 class")

How many students are in the CSC 102 class? 5
There are 5 students in CSC 102 class


In [9]:
#1-D arrays
import numpy as np 
arr = np.array([1,2,3,4,5]) 
print(arr)

[1 2 3 4 5]


In [13]:
#2-D arrays 
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]]) 
print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
#3-D arrays 
import numpy as np 
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [17]:
#Check Number of dimensions
import numpy as np 

a = np.array({42}) 
b = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]) 
c = np.array([[1,2,3],[4,5,6]]) 
d = np.array([1,2,3,4,5]) 

print(a.ndim) 
print(b.ndim) 
print(c.ndim) 
print(d.ndim)

0
3
2
1


In [21]:
#Higher Dimensional arrays

import numpy as np 
arr = np.array([1,2,3,4], ndmin = 8 )  

print(arr) 
print('Number of dimensions : ', arr.ndim)



[[[[[[[[1 2 3 4]]]]]]]]
Number of dimensions :  8


In [22]:
#Access array elements
import numpy as np 
arr = np.array([1,2,3,4]) 
print(arr[1])

2


In [31]:
#Access 2-D arrays
import numpy as np 
arr = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]]) 
print('5th element on 2nd row: ',arr[1,5])

5th element on 2nd row:  11


In [32]:
#Access 3-D arrays
import numpy as np 
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) 
print(arr[0,1,2])

6


In [42]:
#Negative Indexing
import numpy as np 
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]]) 
print('Last element from 2nd dimension: ', arr[1,-1])


Last element from 2nd dimension:  10


In [43]:

# Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


[2 3 4 5]
